; SX1231_Receiver - minimal OOK receiver for an SX1231/RFM69 radio
;
; Wiring below is for an ESP32-S3 with the radio on the listed pins. Adjust the
; RF_MODULE_* pins to match your board.

[platformio]
default_envs = esp32s3-generic
src_dir = .

[libraries]
arduinolog = https://github.com/1technophile/Arduino-Log.git#d13cd80
arduinojson = ArduinoJson
rtl_433_ESP = symlink://../../../rtl_433_ESP

[env]
framework = arduino
platform = espressif32@6.1.0
monitor_filters = esp32_exception_decoder
monitor_speed = 921600
lib_ldf_mode = chain+
lib_deps =
	${libraries.arduinolog}
	${libraries.arduinojson}
	${libraries.rtl_433_ESP}

[env:esp32s3-generic]
platform_packages =
  framework-arduinoespressif32 @ ~3.20007.0
board = esp32s3box

build_flags =
  -D ARDUINO_ESP32S3_DEV
  '-DLOG_LEVEL=LOG_LEVEL_NOTICE'
; *** rtl_433_ESP Options ***
  '-DRF_MODULE_FREQUENCY=433.92'    ; 433MHz ISM band
  '-DOOK_MODULATION=1'              ; False = FSK, True = OOK
  '-DRF_RF69="RF69"'                ; RFM69 / RF69 family transceiver
  '-DMINIMUM_SIGNAL_DURATION=30000' ; one Acurite 592TXR packet is 39.1ms
  '-DOOK_FIXED_THRESHOLD=0x50'      ; OOK threshold for SX1231
; *** RF Module Pin Mapping ***
  '-DRF_MODULE_MISO=1'
  '-DRF_MODULE_MOSI=42'
  '-DRF_MODULE_SCK=41'
  '-DRF_MODULE_CS=40'               ; NSS/CS
  '-DRF_MODULE_RST=39'              ; RESET
  '-DRF_MODULE_DIO0=38'             ; IRQ
  '-DRF_MODULE_DIO1=47'
  '-DRF_MODULE_DIO2=21'             ; continuous data output
  '-DRF_MODULE_INIT_STATUS=true'
; *** RadioLib Options ***
  '-DRADIOLIB_GODMODE'
